config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'application#home', as: :home
  
  get '/categories', to: 'categories#index', as: :categories
  get '/categories/new', to: 'categories#new', as: :new_category
  get '/categories/:id', to: 'categories#show', as: :category
  
 resources :thoughts

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :title, presence: true

	def to_param
		"#{ self.id }-#{ self.title.parameterize }"
	end
end

app/models/thought.rb
class Thought < ActiveRecord::Base
	validates :author, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def home
  	@categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :authenticate_user!
	
	def index
		@categories = Category.all
	end

	def show
		#raise params.inspect
		@category = Category.find(params[:id])
	end

	def new
		@dummy = "dummy data"
	end

end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
	def index
		@thoughts = Thought.all
	end

	def show
		#raise params.inspect
		@thought = Thought.find(params[:id])
	end

	def new
		@thought = Thought.new
	end

	def edit
		@thought = Thought.find(params[:id])
	
	end

	def create
		@thought = Thought.new(params[:thought])
		
		if @thought.save
			redirect_to @thought
		else
			render :new
		end
	end

	def update
		@thought = Thought.find(params[:id])
		
		if @thought.update(params[:thought])
			redirect_to @thought
		else
			render :edit
		end
	end

	def destroy
		@thought = Thought.destroy(params[:id])
		redirect_to thoughts_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/application/_topbar.html.haml
%header
	.logo
		= link_to "thoughts", home_path
	.menu
		%a="home"
		%a="categories"
		%a="thoughts"
		%a="about"
	.login
		- if user_signed_in?
			="hello soul! #{current_user.email}"
			=link_to "lullabies", destroy_user_session_path, method: :delete
		- else
			=link_to "Sign in", new_user_session_path
			=link_to "Sign up", new_user_registration_path

app/views/application/home.html.haml
%main
.title
	%h1= "how are you feeling now?"
.feelings-wrapper
	- @categories.each do |category|
		.feel
			%label
				= link_to category.title, category

app/views/categories/index.html.haml
%h1=link_to "Categories", categories_path

.category-item
	= link_to "New Category", new_category_path

%ul.categories
	- @categories.each do |cat|
		%li.category-item
			= link_to cat.title, cat

app/views/categories/new.html.haml
= @dummy

app/views/categories/show.html.haml
%p=link_to "Back to categories", categories_path
%h1= @category.title

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Indie+Flower", :rel=>"stylesheet"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag


  %body
    = render "application/topbar"
  %p.notice
    = notice
  %p.alert
    = alert
    
    = yield

app/views/thoughts/edit.html.haml
= form_for @thought do |f|
	- if @thought.errors.any?
		%ul
			%li= "Hey dude! you have #{@thought.errors.size} error(s)"
			- @thought.errors.full_messages.each do |error|
				%li= error

	= f.label :category_id
	= f.text_field :category_id

	= f.label :author
	= f.text_field :author

	= f.label :thought
	= f.text_area :thought

	= f.button :clear, type: :reset
	= f.submit

app/views/thoughts/index.html.haml
%h1=link_to "Thoughts", thoughts_path

.thought-item
	= link_to "Share a thought", new_thought_path

%ul.thoughts
	- @thoughts.each do |thought|
		%li.category-item
			= link_to thought.author, thought
			= link_to ' [x]', thought, method: :delete

app/views/thoughts/new.html.haml
= form_for @thought do |f|
	- if @thought.errors.any?
		%ul
			%li= "Hey dude! you have #{@thought.errors.size} error(s)"
			- @thought.errors.full_messages.each do |error|
				%li= error

	= f.label :category_id
	= f.text_field :category_id

	= f.label :author
	= f.text_field :author

	= f.label :thought
	= f.text_area :thought

	= f.button :clear, type: :reset
	= f.submit

app/views/thoughts/show.html.haml
%p=link_to "Back to thoughts", thoughts_path
%h1= @thought.author
%p= @thought.thought